#!/usr/bin/env bash
# Generates the narration locally with macOS `say` (voice chosen with the user: Samantha, compact).
# Writes public/vo/vo_NN.wav and src/vo.generated.ts with each line's text and duration.
set -euo pipefail
cd "$(dirname "$0")/.."
VOICE="${VOICE:-Samantha}"
RATE="${RATE:-178}"
mkdir -p public/vo
echo "// Generated by scripts/make-vo.sh. Do not edit." > src/vo.generated.ts
echo "export const VO: Record<string, { file: string; text: string; seconds: number }> = {" >> src/vo.generated.ts
while IFS=$'\t' read -r id text; do
  [ -z "$id" ] && continue
  # Spoken form may spell out letters; the subtitle form restores them.
  say -v "$VOICE" -r "$RATE" -o "public/vo/vo_$id.aiff" "$text"
  ffmpeg -y -loglevel error -i "public/vo/vo_$id.aiff" -ar 48000 -ac 1 "public/vo/vo_$id.wav"
  rm "public/vo/vo_$id.aiff"
  d=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "public/vo/vo_$id.wav")
  sub=$(printf '%s' "$text" | sed -e 's/Chat G P T/ChatGPT/g' -e 's/O C R/OCR/g' -e 's/Option Space/Option-Space/g' -e 's/Option Command V/⌥⌘V/g')
  printf '  "%s": { file: "vo/vo_%s.wav", text: %s, seconds: %s },\n' "$id" "$id" "$(node -e 'process.stdout.write(JSON.stringify(process.argv[1]))' "$sub")" "$d" >> src/vo.generated.ts
done < vo/lines.tsv
echo "};" >> src/vo.generated.ts
echo "narration written ($VOICE @ $RATE wpm)"
