// Generated by scripts/sync-captures.mjs. Do not edit: run `npm run sync`.
export type SpeedSpan = { from: number; to: number; speed: number };
export type Clip = { file: string; seconds?: number; aspect?: number; speedSpans?: SpeedSpan[]; marks?: Record<string, number> } | null;
export const clips: Record<string, Clip> = {
  "R1-wifi": null,
  "R2-ask": null,
  "R3-verify": null,
  "R4-redact": null,
  "R5-leak": null
};
