// Generated by scripts/make-vo.sh. Do not edit.
export const VO: Record<string, { file: string; text: string; seconds: number }> = {
  "01": { file: "vo/vo_01.wav", text: "HR teams handle government IDs, salaries and home addresses every day. And those files keep getting pasted into cloud AI.", seconds: 7.427542 },
  "02": { file: "vo/vo_02.wav", text: "This is Gel. Private AI for your Mac. First, Wi-Fi off.", seconds: 4.027854 },
  "03": { file: "vo/vo_03.wav", text: "Press Option-Space, and ask in Taglish.", seconds: 2.540833 },
  "04": { file: "vo/vo_04.wav", text: "Gel answers with its sources, right on this Mac.", seconds: 2.747229 },
  "05": { file: "vo/vo_05.wav", text: "Click a source, and the exact passage opens, highlighted.", seconds: 3.505313 },
  "06": { file: "vo/vo_06.wav", text: "Sharing files? Gel burns in redactions, even on scans. Originals stay untouched.", seconds: 5.665188 },
  "07": { file: "vo/vo_07.wav", text: "Now copy an employee record into ChatGPT. Gel catches it, and ⌥⌘V pastes placeholders instead.", seconds: 6.553292 },
  "08": { file: "vo/vo_08.wav", text: "Speech, OCR, search and answers all run locally. The cloud only sees redacted text, and only if you allow it.", seconds: 7.317250 },
  "09": { file: "vo/vo_09.wav", text: "Gel. Private AI for your files.", seconds: 2.139688 },
};
